import type { Simulation } from "../engine/types";

export const microscopeUse: Simulation = {
  id: "microscope-use",
  title: "Using a Light Microscope",
  subtitle: "Focus & Magnification Techniques",
  category: "Biology",
  description: "Learn to properly focus a light microscope. Start with the lowest objective, find the specimen, then increase magnification step by step.",
  difficulty: "Beginner",
  estimatedMinutes: 6,
  icon: "🔬",
  equipment: [
    { id: "microscope", type: "microscope", label: "Light Microscope", draggable: false, initialState: { magnification: 4, focusLevel: 0, hasSlide: false } },
    { id: "slide", type: "slide", label: "Prepared Slide (Letter 'e')", draggable: true, initialState: { specimen: "e" } },
    { id: "coarse-knob", type: "knob", label: "Coarse Focus", initialState: { value: 0 } },
    { id: "fine-knob", type: "knob", label: "Fine Focus", initialState: { value: 0 } },
    { id: "objective-4x", type: "objective", label: "4× Scanning", initialState: { power: 4 } },
    { id: "objective-10x", type: "objective", label: "10× Low Power", initialState: { power: 10 } },
    { id: "objective-40x", type: "objective", label: "40× High Dry", initialState: { power: 40 } },
  ],
  initialLayout: [
    { id: "microscope", x: 240, y: 140, scale: 1.3 },
    { id: "slide", x: 60, y: 200, scale: 1 },
    { id: "coarse-knob", x: 500, y: 180, scale: 0.9 },
    { id: "fine-knob", x: 500, y: 280, scale: 0.9 },
    { id: "objective-4x", x: 500, y: 370, scale: 0.8 },
    { id: "objective-10x", x: 580, y: 370, scale: 0.8 },
    { id: "objective-40x", x: 660, y: 370, scale: 0.8 },
  ],
  steps: [
    {
      id: "place-slide",
      instruction: "Place the prepared slide on the microscope stage.",
      hint: "Drag the slide onto the microscope.",
      trigger: { type: "collision", items: ["slide", "microscope"] },
      result: { visual: "slide-placed", message: "Slide secured! The letter 'e' is your specimen. Notice it appears upside down through the microscope." },
    },
    {
      id: "start-4x",
      instruction: "Start with the 4× scanning objective (lowest power).",
      hint: "Click the 4× objective.",
      trigger: { type: "click", target: "objective-4x" },
      result: { visual: "objective-4x", data: { magnification: 4 }, message: "4× objective selected. Total magnification = 4× × 10× (eyepiece) = 40×." },
    },
    {
      id: "coarse-focus",
      instruction: "Use the coarse focus knob to bring the specimen into approximate focus.",
      hint: "Turn the coarse focus knob.",
      trigger: { type: "value-change", target: "coarse-knob", above: 60 },
      result: { visual: "coarse-focused", message: "Specimen is now visible but not sharp. Coarse adjustment moves the stage a large distance." },
    },
    {
      id: "fine-focus",
      instruction: "Use the fine focus knob for a sharp, crisp image.",
      hint: "Turn the fine focus knob slightly.",
      trigger: { type: "value-change", target: "fine-knob", above: 50 },
      result: { visual: "fine-focused", message: "Perfect focus at 40×! The letter 'e' appears inverted and reversed. Fine adjustment moves the stage very slightly." },
    },
    {
      id: "switch-10x",
      instruction: "Switch to the 10× low power objective.",
      hint: "Click the 10× objective.",
      trigger: { type: "click", target: "objective-10x" },
      result: { visual: "objective-10x", data: { magnification: 10 }, message: "Total magnification now 100×. The field of view is smaller and the image is darker." },
    },
    {
      id: "refine-10x",
      instruction: "Refine the focus at 10× using the fine focus knob.",
      trigger: { type: "value-change", target: "fine-knob", above: 50 },
      result: { visual: "focused-10x", message: "Sharp at 100×! You can see the individual cells of the letter printed on paper." },
    },
    {
      id: "switch-40x",
      instruction: "Switch to the 40× high dry objective.",
      hint: "Be careful — the lens is very close to the slide.",
      trigger: { type: "click", target: "objective-40x" },
      result: { visual: "objective-40x", data: { magnification: 40 }, message: "Total magnification now 400×! The working distance is very small — do NOT use coarse focus." },
    },
    {
      id: "final-focus",
      instruction: "Focus carefully at 400× using ONLY the fine focus knob.",
      trigger: { type: "value-change", target: "fine-knob", above: 50 },
      result: {
        visual: "focused-40x",
        data: { isComplete: true },
        message: "Excellent! You can now see individual ink particles and paper fibers at 400× magnification. Never use coarse focus at high power!",
      },
    },
  ],
};
