import type { GateDef, GateType } from "./types";

function mkIn(type: GateType, label: string, outs: string[], w = 70, h = 44): GateDef {
  return { type, label, category: "Input Controls", inputs: [], outputs: outs.map(id => ({ id, label: id, side: "right" as const })), w, h };
}
function mkOut(type: GateType, label: string, ins: string[], w = 70, h = 60): GateDef {
  return { type, label, category: "Output Controls", inputs: ins.map(id => ({ id, label: id, side: "left" as const })), outputs: [], w, h };
}
function mkG(type: GateType, label: string, ins: string[], outs: {id:string;lb:string}[], w = 90, h = 52): GateDef {
  return { type, label, category: "Logic Gates", inputs: ins.map(id => ({ id, label: id.toUpperCase(), side: "left" as const })), outputs: outs.map(o => ({ id: o.id, label: o.lb, side: "right" as const })), w, h };
}
function mkC(type: GateType, label: string, ins: string[], outs: string[], w = 100, h = 72): GateDef {
  return { type, label, category: "Combinational", inputs: ins.map(id => ({ id, label: id, side: "left" as const })), outputs: outs.map(id => ({ id, label: id, side: "right" as const })), w, h };
}
function mkS(type: GateType, label: string, ins: string[], outs: string[], w = 100, h = 72): GateDef {
  return { type, label, category: "Sequential", inputs: ins.map(id => ({ id, label: id, side: "left" as const })), outputs: outs.map(id => ({ id, label: id, side: "right" as const })), w, h };
}

const Q = {id:"out",lb:"Q"};
const QQ = [{id:"q",lb:"Q"},{id:"qn",lb:"Q'"}];
const a = (n:number) => Array.from({length:n},(_,i)=>`a${i}`);
const b = (n:number) => Array.from({length:n},(_,i)=>`b${i}`);
const d = (n:number) => Array.from({length:n},(_,i)=>`d${i}`);
const o = (n:number) => Array.from({length:n},(_,i)=>`o${i}`);
const q = (n:number) => Array.from({length:n},(_,i)=>`q${i}`);
const s = (n:number) => Array.from({length:n},(_,i)=>`s${i}`);
const p = (n:number) => Array.from({length:n},(_,i)=>`p${i}`);
const qObj = (n:number) => Array.from({length:n},(_,i)=>({id:`q${i}`,lb:`Q${i}`}));
const oObj = (n:number) => Array.from({length:n},(_,i)=>({id:`o${i}`,lb:`O${i}`}));

export const GATE_DEFS: Record<GateType, GateDef> = {
  // ====== Input Controls ======
  "const-0": {type:"const-0",label:"0",category:"Input Controls",inputs:[],outputs:[{id:"out",label:"0",side:"right"}],w:60,h:40},
  "const-1": {type:"const-1",label:"1",category:"Input Controls",inputs:[],outputs:[{id:"out",label:"1",side:"right"}],w:60,h:40},
  toggle: {type:"toggle",label:"Switch",category:"Input Controls",inputs:[],outputs:[{id:"out",label:"Q",side:"right"}],w:70,h:44},
  button: {type:"button",label:"Button",category:"Input Controls",inputs:[],outputs:[{id:"out",label:"Q",side:"right"}],w:70,h:44},
  clock: {type:"clock",label:"Clock",category:"Input Controls",inputs:[],outputs:[{id:"out",label:"CLK",side:"right"}],w:70,h:44},
  "dip-switch": {type:"dip-switch",label:"DIP Switch",category:"Input Controls",inputs:[],outputs:[...Array.from({length:8},(_,i)=>({id:`o${i}`,label:`${i}`,side:"right" as const}))],w:80,h:90},
  keypad: {type:"keypad",label:"Keypad",category:"Input Controls",inputs:[],outputs:["d0","d1","d2","d3","valid"].map(id=>({id,label:id,side:"right" as const})),w:80,h:90},
  "analog-in": {type:"analog-in",label:"Analog In",category:"Input Controls",inputs:[],outputs:["d0","d1","d2","d3"].map(id=>({id,label:id,side:"right" as const})),w:80,h:70},
  random: mkIn("random","Random",["out"]),
  "push-button": mkIn("push-button","Push Btn",["out"]),
  "pulse-gen": mkIn("pulse-gen","Pulse Gen",["out"],70,44),
  "edge-det": mkIn("edge-det","Rise Det",["out"],70,44),
  "edge-det-f": mkIn("edge-det-f","Fall Det",["out"],70,44),
  "voltage-src-4": mkIn("voltage-src-4","Volt Src",["d0","d1","d2","d3"],80,60),
  "data-bus-in": mkIn("data-bus-in","Data In",["d0","d1","d2","d3","d4","d5","d6","d7"],80,90),
  "addr-input": mkIn("addr-input","Addr In",["a0","a1","a2","a3"],80,60),
  "step-input": mkIn("step-input","Step In",["d0","d1"],70,50),
  "status-in": mkIn("status-in","Status In",["s0","s1","s2","s3","s4","s5","s6","s7"],80,90),
  "control-in": mkIn("control-in","Ctrl In",["c0","c1","c2","c3"],80,60),
  "strobe-in": mkIn("strobe-in","Strobe",["out"],70,44),
  "ready-in": mkIn("ready-in","Ready",["out"],70,44),
  "ack-in": mkIn("ack-in","ACK",["out"],70,44),
  "busy-in": mkIn("busy-in","Busy",["out"],70,44),
  "interrupt-in": mkIn("interrupt-in","IRQ",["out"],70,44),
  "dma-in": mkIn("dma-in","DMA",["out"],70,44),
  "hold-in": mkIn("hold-in","Hold",["out"],70,44),
  "bus-req-in": mkIn("bus-req-in","BusReq",["out"],70,44),
  "test-mode": mkIn("test-mode","Test",["out"],70,44),
  "enable-all": mkIn("enable-all","Enable",["out"],70,44),
  "global-reset": mkIn("global-reset","Reset",["out"],70,44),

  // ====== Output Controls ======
  bulb: mkOut("bulb","Bulb",["in"]),
  "hex-display": {type:"hex-display",label:"Hex Display",category:"Output Controls",inputs:["a","b","c","d"].map(id=>({id,label:id,side:"left" as const})),outputs:[],w:70,h:60},
  led: {type:"led",label:"LED",category:"Output Controls",inputs:["r","g","b"].map(id=>({id,label:id,side:"left" as const})),outputs:[],w:60,h:56},
  "7-segment": {type:"7-segment",label:"7-Segment",category:"Output Controls",inputs:["a","b","c","d","e","f","g"].map(id=>({id,label:id,side:"left" as const})),outputs:[],w:70,h:80},
  buzzer: mkOut("buzzer","Buzzer",["in"]),
  "bar-graph": {type:"bar-graph",label:"Bar Graph",category:"Output Controls",inputs:[...Array.from({length:8},(_,i)=>({id:`i${i}`,label:`${i}`,side:"left" as const}))],outputs:[],w:80,h:70},
  "tri-led": mkOut("tri-led","RGB LED",["r","g","b"],60,60),
  "stepper-motor": mkOut("stepper-motor","Stepper",["a","b","c","d"],70,64),
  "servo-motor": mkOut("servo-motor","Servo",["in","en"],70,56),
  "lcd-display": mkOut("lcd-display","LCD",["d0","d1","d2","d3","d4","d5","d6","d7"],90,70),
  "status-led": mkOut("status-led","Status",["in","en"],60,50),
  "traffic-light": mkOut("traffic-light","Traffic",["r","y","g"],56,80),
  "digit-display": mkOut("digit-display","Digit",["d0","d1","d2","d3"],60,64),
  "dot-matrix": mkOut("dot-matrix","Dot Matrix",["p0","p1","p2","p3","p4","p5","p6","p7","p8","p9","p10","p11","p12","p13","p14","p15","p16","p17","p18","p19","p20","p21","p22","p23","p24"],100,100),
  "scope-output": mkOut("scope-output","Scope",["in","trig"],120,80),
  "indicator-panel": mkOut("indicator-panel","Ind Panel",["i0","i1","i2","i3","i4","i5","i6","i7"],100,70),
  "seven-seg-4": mkOut("seven-seg-4","4-Dig 7seg",["a","b","c","d","e","f","g","d0","d1","d2","d3"],100,80),
  "ascii-display": mkOut("ascii-display","ASCII Disp",["b0","b1","b2","b3","b4","b5","b6"],80,70),
  "signal-analyzer": mkOut("signal-analyzer","Analyzer",["in","clk"],120,80),
  "voltmeter": mkOut("voltmeter","Voltmeter",["in"],70,60),
  "ammeter": mkOut("ammeter","Ammeter",["in"],70,60),
  "clock-display": mkOut("clock-display","Clock",["h0","h1","m0","m1","s0","s1"],90,70),
  "thermometer-out": mkOut("thermometer-out","Temp",["in"],60,64),
  "tachometer": mkOut("tachometer","Tacho",["in"],70,60),
  "power-meter": mkOut("power-meter","Power",["v","i"],70,60),
  "data-latch-disp": mkOut("data-latch-disp","Data Disp",["d0","d1","d2","d3","d4","d5","d6","d7"],90,70),

  // ====== Logic Gates ======
  buffer: mkG("buffer","Buffer",["a"],[Q]),
  not: mkG("not","NOT",["a"],[Q]),
  and: mkG("and","AND",["a","b"],[Q]),
  nand: mkG("nand","NAND",["a","b"],[Q]),
  or: mkG("or","OR",["a","b"],[Q]),
  nor: mkG("nor","NOR",["a","b"],[Q]),
  xor: mkG("xor","XOR",["a","b"],[Q]),
  xnor: mkG("xnor","XNOR",["a","b"],[Q]),
  xor3: mkG("xor3","XOR3",["a","b","c"],[Q],90,64),
  xnor3: mkG("xnor3","XNOR3",["a","b","c"],[Q],90,64),
  nand3: mkG("nand3","NAND3",["a","b","c"],[Q],90,64),
  nor3: mkG("nor3","NOR3",["a","b","c"],[Q],90,64),
  or3: mkG("or3","OR3",["a","b","c"],[Q],90,64),
  aoi: mkG("aoi","AOI",["a","b","c","d"],[Q],100,72),
  oai: mkG("oai","OAI",["a","b","c","d"],[Q],100,72),
  ao: mkG("ao","AND-OR",["a","b","c","d"],[Q],100,72),
  "buffer-inv": {type:"buffer-inv",label:"BUF+INV",category:"Logic Gates",inputs:[{id:"a",label:"A",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:80,h:56},
  "mux2-inv": {type:"mux2-inv",label:"MUX2+INV",category:"Logic Gates",inputs:["i0","i1","sel"].map(id=>({id,label:id.toUpperCase(),side:"left" as const})),outputs:[{id:"y",label:"Y",side:"right"},{id:"yn",label:"Y'",side:"right"}],w:90,h:68},
  "and3": mkG("and3","AND3",["abc"],[Q],100,64),
  "and4": mkG("and4","AND4",["abcd"],[Q],100,72),
  "and5": mkG("and5","AND5",["abcde"],[Q],110,88),
  "and6": mkG("and6","AND6",["abcdef"],[Q],110,88),
  "and8": mkG("and8","AND8",["abcdefgh"],[Q],110,100),
  "or4": mkG("or4","OR4",["abcd"],[Q],100,72),
  "or5": mkG("or5","OR5",["abcde"],[Q],110,88),
  "or6": mkG("or6","OR6",["abcdef"],[Q],110,88),
  "or8": mkG("or8","OR8",["abcdefgh"],[Q],110,100),
  "nand4": mkG("nand4","NAND4",["abcd"],[Q],100,72),
  "nand5": mkG("nand5","NAND5",["abcde"],[Q],110,88),
  "nand6": mkG("nand6","NAND6",["abcdef"],[Q],110,88),
  "nand8": mkG("nand8","NAND8",["abcdefgh"],[Q],110,100),
  "nor4": mkG("nor4","NOR4",["abcd"],[Q],100,72),
  "nor5": mkG("nor5","NOR5",["abcde"],[Q],110,88),
  "nor6": mkG("nor6","NOR6",["abcdef"],[Q],110,88),
  "nor8": mkG("nor8","NOR8",["abcdefgh"],[Q],110,100),
  "xor4": mkG("xor4","XOR4",["abcd"],[Q],100,72),
  "xor5": mkG("xor5","XOR5",["abcde"],[Q],110,88),
  "xor6": mkG("xor6","XOR6",["abcdef"],[Q],110,88),
  "xor8": mkG("xor8","XOR8",["abcdefgh"],[Q],110,100),
  "xnor4": mkG("xnor4","XNOR4",["abcd"],[Q],100,72),
  "xnor5": mkG("xnor5","XNOR5",["abcde"],[Q],110,88),
  "xnor6": mkG("xnor6","XNOR6",["abcdef"],[Q],110,88),
  "xnor8": mkG("xnor8","XNOR8",["abcdefgh"],[Q],110,100),
  "buffer2": {type:"buffer2",label:"BUFx2",category:"Logic Gates",inputs:[{id:"a",label:"A",side:"left"}],outputs:[{id:"q0",label:"Q0",side:"right"},{id:"q1",label:"Q1",side:"right"}],w:80,h:56},
  "buffer4": {type:"buffer4",label:"BUFx4",category:"Logic Gates",inputs:[{id:"a",label:"A",side:"left"}],outputs:[...Array.from({length:4},(_,i)=>({id:`q${i}`,label:`Q${i}`,side:"right" as const}))],w:80,h:72},
  "not2": {type:"not2",label:"INVx2",category:"Logic Gates",inputs:[{id:"a",label:"A",side:"left"}],outputs:[{id:"q0",label:"Q0",side:"right"},{id:"q1",label:"Q1",side:"right"}],w:80,h:56},
  "not4": {type:"not4",label:"INVx4",category:"Logic Gates",inputs:[{id:"a",label:"A",side:"left"}],outputs:[...Array.from({length:4},(_,i)=>({id:`q${i}`,label:`Q${i}`,side:"right" as const}))],w:80,h:72},
  "and-or-inv": mkG("and-or-inv","AOI21",["a","b","c"],[Q],90,64),
  "or-and": mkG("or-and","OR-AND",["a","b","c","d"],[Q],100,72),
  "or-and-inv": mkG("or-and-inv","OAI21",["a","b","c"],[Q],90,64),
  aoai: mkG("aoai","AOAI",["a","b","c","d","e"],[Q],100,84),
  oaoi: mkG("oaoi","OAOI",["a","b","c","d","e"],[Q],100,84),
  majority: mkG("majority","Majority",["a","b","c"],[Q],90,64),
  parity3: mkG("parity3","Parity3",["a","b","c"],[Q],90,64),
  "tri-state": mkG("tri-state","Tri-State",["a","en"],[Q],90,56),
  "tri-state-inv": mkG("tri-state-inv","TS-INV",["a","en"],[Q],90,56),
  "open-drain": mkG("open-drain","Open Drain",["a"],[Q],80,48),
  "inverter-bank-4": mkG("inverter-bank-4","INV×4",a(4),qObj(4),90,72),
  "buffer-bank-4": mkG("buffer-bank-4","BUF×4",a(4),qObj(4),90,72),
  "and-bank-4": mkG("and-bank-4","AND×4",a(8),qObj(4),100,92),
  "or-bank-4": mkG("or-bank-4","OR×4",a(8),qObj(4),100,92),
  "xor-bank-4": mkG("xor-bank-4","XOR×4",a(8),qObj(4),100,92),
  "nand-bank-4": mkG("nand-bank-4","NAND×4",a(8),qObj(4),100,92),
  "nor-bank-4": mkG("nor-bank-4","NOR×4",a(8),qObj(4),100,92),
  "constant-bank-4": mkG("constant-bank-4","Const×4",["v0","v1","v2","v3"],qObj(4),90,72),

  // ====== Combinational ======
  "half-adder": {type:"half-adder",label:"Half Adder",category:"Combinational",inputs:[{id:"a",label:"A",side:"left"},{id:"b",label:"B",side:"left"}],outputs:[{id:"sum",label:"Sum",side:"right"},{id:"cout",label:"Cout",side:"right"}],w:100,h:64},
  "full-adder": {type:"full-adder",label:"Full Adder",category:"Combinational",inputs:[{id:"a",label:"A",side:"left"},{id:"b",label:"B",side:"left"},{id:"cin",label:"Cin",side:"left"}],outputs:[{id:"sum",label:"Sum",side:"right"},{id:"cout",label:"Cout",side:"right"}],w:100,h:72},
  "half-subtractor": {type:"half-subtractor",label:"Half Sub",category:"Combinational",inputs:[{id:"a",label:"A",side:"left"},{id:"b",label:"B",side:"left"}],outputs:[{id:"diff",label:"D",side:"right"},{id:"borrow",label:"Bout",side:"right"}],w:100,h:64},
  "full-subtractor": {type:"full-subtractor",label:"Full Sub",category:"Combinational",inputs:[{id:"a",label:"A",side:"left"},{id:"b",label:"B",side:"left"},{id:"bin",label:"Bin",side:"left"}],outputs:[{id:"diff",label:"D",side:"right"},{id:"borrow",label:"Bout",side:"right"}],w:100,h:72},
  mux2: {type:"mux2",label:"2:1 MUX",category:"Combinational",inputs:[{id:"i0",label:"I0",side:"left"},{id:"i1",label:"I1",side:"left"},{id:"sel",label:"S",side:"left"}],outputs:[{id:"out",label:"Y",side:"right"}],w:90,h:68},
  mux4: {type:"mux4",label:"4:1 MUX",category:"Combinational",inputs:[{id:"i0",label:"I0",side:"left"},{id:"i1",label:"I1",side:"left"},{id:"i2",label:"I2",side:"left"},{id:"i3",label:"I3",side:"left"},{id:"s0",label:"S0",side:"left"},{id:"s1",label:"S1",side:"left"}],outputs:[{id:"out",label:"Y",side:"right"}],w:100,h:90},
  decoder: {type:"decoder",label:"2:4 Decoder",category:"Combinational",inputs:[{id:"a",label:"A",side:"left"},{id:"b",label:"B",side:"left"}],outputs:[...o(4).map((id,i)=>({id,label:`D${i}`,side:"right" as const}))],w:100,h:80},
  "dec-2to4": {type:"dec-2to4",label:"2:4 Dec+EN",category:"Combinational",inputs:[{id:"a",label:"A",side:"left"},{id:"b",label:"B",side:"left"},{id:"en",label:"EN",side:"left"}],outputs:[...o(4).map((id,i)=>({id,label:`D${i}`,side:"right" as const}))],w:100,h:84},
  "prio-enc-4to2": {type:"prio-enc-4to2",label:"4:2 PEnc",category:"Combinational",inputs:["i0","i1","i2","i3"].map(id=>({id,label:id.toUpperCase(),side:"left" as const})),outputs:[{id:"y0",label:"Y0",side:"right"},{id:"y1",label:"Y1",side:"right"},{id:"v",label:"V",side:"right"}],w:100,h:80},
  "full-comp": {type:"full-comp",label:"1-bit Comp",category:"Combinational",inputs:[{id:"a",label:"A",side:"left"},{id:"b",label:"B",side:"left"}],outputs:[{id:"gt",label:"A>B",side:"right"},{id:"eq",label:"A=B",side:"right"},{id:"lt",label:"A<B",side:"right"}],w:100,h:64},
  "cla-unit": {type:"cla-unit",label:"CLA Unit",category:"Combinational",inputs:["p0","g0","p1","g1","cin"].map(id=>({id,label:id.toUpperCase(),side:"left" as const})),outputs:[{id:"c1",label:"C1",side:"right"},{id:"c2",label:"C2",side:"right"},{id:"c3",label:"C3",side:"right"}],w:100,h:84},
  "adder-4bit": mkC("adder-4bit","4-bit Adder",[...a(4),...b(4),"cin"],[...s(4),"cout"],120,112),
  "adder-8bit": mkC("adder-8bit","8-bit Adder",[...a(8),...b(8),"cin"],[...s(8),"cout"],140,140),
  "subtractor-4bit": mkC("subtractor-4bit","4-bit Sub",[...a(4),...b(4),"bin"],[...d(4),"bout"],120,112),
  "subtractor-8bit": mkC("subtractor-8bit","8-bit Sub",[...a(8),...b(8),"bin"],[...d(8),"bout"],140,140),
  "multiplier-4bit": mkC("multiplier-4bit","4-bit Mul",[...a(4),...b(4)],p(8),120,100),
  "multiplier-8bit": mkC("multiplier-8bit","8-bit Mul",[...a(8),...b(8)],p(16),140,140),
  "divider-4bit": mkC("divider-4bit","4-bit Div",[...a(4),...b(4)],[...q(4),...o(4)],120,100),
  "comparator-4bit": mkC("comparator-4bit","4-bit Comp",[...a(4),...b(4)],["gt","eq","lt"],120,100),
  "comparator-8bit": mkC("comparator-8bit","8-bit Comp",[...a(8),...b(8)],["gt","eq","lt"],140,130),
  "cla-adder-4": mkC("cla-adder-4","4-bit CLA",[...a(4),...b(4),"cin"],[...s(4),"cout"],120,112),
  "carry-select-4": mkC("carry-select-4","CSA 4-bit",[...a(4),...b(4),"cin"],[...s(4),"cout"],120,112),
  "kogge-stone-4": mkC("kogge-stone-4","KS 4-bit",[...a(4),...b(4),"cin"],[...s(4),"cout"],120,112),
  "brent-kung-4": mkC("brent-kung-4","BK 4-bit",[...a(4),...b(4),"cin"],[...s(4),"cout"],120,112),
  "wallace-mul-4": mkC("wallace-mul-4","Wallace Mul",[...a(4),...b(4)],p(8),120,100),
  "booth-mul-4": mkC("booth-mul-4","Booth Mul",[...a(4),...b(4)],p(8),120,100),
  mux8: mkC("mux8","8:1 MUX",[...Array.from({length:8},(_,i)=>`i${i}`),...Array.from({length:3},(_,i)=>`s${i}`)],["out"],120,112),
  mux16: mkC("mux16","16:1 MUX",[...Array.from({length:16},(_,i)=>`i${i}`),...Array.from({length:4},(_,i)=>`s${i}`)],["out"],130,148),
  "demux1to2": mkC("demux1to2","1:2 DEMUX",["in","sel"],["o0","o1"],90,56),
  "demux1to4": mkC("demux1to4","1:4 DEMUX",["in","s0","s1"],o(4),100,72),
  "demux1to8": mkC("demux1to8","1:8 DEMUX",["in","s0","s1","s2"],o(8),110,100),
  "encoder-8to3": mkC("encoder-8to3","8:3 Enc",Array.from({length:8},(_,i)=>`i${i}`),["y0","y1","y2","v"],110,100),
  "encoder-16to4": mkC("encoder-16to4","16:4 Enc",Array.from({length:16},(_,i)=>`i${i}`),["y0","y1","y2","y3","v"],130,140),
  "prio-encoder-8to3": mkC("prio-encoder-8to3","8:3 PEnc",Array.from({length:8},(_,i)=>`i${i}`),["y0","y1","y2","v"],110,100),
  "prio-encoder-16to4": mkC("prio-encoder-16to4","16:4 PEnc",Array.from({length:16},(_,i)=>`i${i}`),["y0","y1","y2","y3","v"],130,140),
  "decoder-3to8": mkC("decoder-3to8","3:8 Dec",["a","b","c"],o(8),110,96),
  "decoder-4to16": mkC("decoder-4to16","4:16 Dec",["a","b","c","d"],Array.from({length:16},(_,i)=>`o${i}`),130,140),
  "bcd-to-binary": mkC("bcd-to-binary","BCD→Bin",Array.from({length:4},(_,i)=>`b${i}`),o(4),100,72),
  "binary-to-bcd": mkC("binary-to-bcd","Bin→BCD",Array.from({length:4},(_,i)=>`b${i}`),["d0","d1","d2","d3"],100,72),
  "bcd-to-7seg": mkC("bcd-to-7seg","BCD→7Seg",Array.from({length:4},(_,i)=>`b${i}`),["a","b","c","d","e","f","g"],100,84),
  "gray-to-binary": mkC("gray-to-binary","Gray→Bin",Array.from({length:4},(_,i)=>`g${i}`),Array.from({length:4},(_,i)=>`b${i}`),100,72),
  "binary-to-gray": mkC("binary-to-gray","Bin→Gray",Array.from({length:4},(_,i)=>`b${i}`),Array.from({length:4},(_,i)=>`g${i}`),100,72),
  "alu-4bit": mkC("alu-4bit","4-bit ALU",[...a(4),...b(4),"s0","s1","cin"],[...o(4),"cout"],120,120),
  "alu-8bit": mkC("alu-8bit","8-bit ALU",[...a(8),...b(8),"s0","s1","cin"],[...o(8),"cout"],140,156),
  "sign-ext-4to8": mkC("sign-ext-4to8","Sign Ext",a(4),o(8),100,72),
  "zero-ext-4to8": mkC("zero-ext-4to8","Zero Ext",a(4),o(8),100,72),
  "bit-reverse-4": mkC("bit-reverse-4","Bit Rev",a(4),o(4),100,72),
  "byte-swap-16": mkC("byte-swap-16","Byte Swap",Array.from({length:16},(_,i)=>`a${i}`),Array.from({length:16},(_,i)=>`o${i}`),120,140),
  "shift-left-4": mkC("shift-left-4","ShL 4",[...a(4),"s0","s1"],o(4),100,84),
  "shift-right-4": mkC("shift-right-4","ShR 4",[...a(4),"s0","s1"],o(4),100,84),
  "arith-shift-right-4": mkC("arith-shift-right-4","ASR 4",[...a(4),"s0","s1"],o(4),100,84),
  "rotate-left-4": mkC("rotate-left-4","RotL 4",[...a(4),"s0","s1"],o(4),100,84),
  "rotate-right-4": mkC("rotate-right-4","RotR 4",[...a(4),"s0","s1"],o(4),100,84),
  "barrel-shifter-4": mkC("barrel-shifter-4","Barrel 4",[...a(4),"s0","s1","dir"],o(4),110,92),
  "barrel-shifter-8": mkC("barrel-shifter-8","Barrel 8",[...a(8),"s0","s1","s2","dir"],o(8),130,116),
  "popcount-8": mkC("popcount-8","PopCnt 8",a(8),["o0","o1","o2"],110,100),
  "leading-zeros-8": mkC("leading-zeros-8","CLZ 8",a(8),o(4),110,100),
  "trailing-zeros-8": mkC("trailing-zeros-8","CTZ 8",a(8),o(4),110,100),
  "mask-gen-4": mkC("mask-gen-4","Mask Gen",["n","s0","s1"],o(4),100,68),
  "abs-value-8": mkC("abs-value-8","ABS 8",a(8),o(8),110,100),
  "negate-8": mkC("negate-8","NEG 8",a(8),o(8),110,100),
  "sqrt-approx-4": mkC("sqrt-approx-4","√≈ 4",a(4),o(2),100,72),
  "log2-approx": mkC("log2-approx","log₂≈",a(4),o(2),100,72),
  "min-2": mkC("min-2","MIN",[...a(4),...b(4)],o(4),110,100),
  "max-2": mkC("max-2","MAX",[...a(4),...b(4)],o(4),110,100),
  "clamp-8": mkC("clamp-8","Clamp 8",[...a(8),"lo","hi"],o(8),120,116),
  "saturate-8": mkC("saturate-8","Sat 8",[...a(8),...b(8)],[...o(8),"sat"],130,130),
  "parity-check-8": mkC("parity-check-8","Par Chk 8",a(8),["out"],110,100),
  "parity-gen-valid": mkC("parity-gen-valid","Par Gen+V",a(8),["p","v"],110,100),
  "hamming-enc-4": mkC("hamming-enc-4","Ham Enc",Array.from({length:4},(_,i)=>`d${i}`),Array.from({length:7},(_,i)=>`c${i}`),100,72),
  "hamming-dec-7": mkC("hamming-dec-7","Ham Dec",Array.from({length:7},(_,i)=>`c${i}`),[...Array.from({length:4},(_,i)=>`d${i}`),"err"],100,84),
  "crc-gen-4": mkC("crc-gen-4","CRC Gen",Array.from({length:8},(_,i)=>`d${i}`),Array.from({length:4},(_,i)=>`c${i}`),110,100),
  "crc-check-4": mkC("crc-check-4","CRC Chk",Array.from({length:12},(_,i)=>`d${i}`),["ok"],120,120),
  "checksum-4": mkC("checksum-4","Checksum",[...a(4),...b(4)],s(4),110,100),
  "lfsr-4": mkS("lfsr-4","LFSR 4",["clk","en","rst"],o(4),100,72),
  "bit-slice-4": mkC("bit-slice-4","Bit Slice",[...a(8),"lo","hi"],o(4),110,110),
  "width-conv-4to8": mkC("width-conv-4to8","4→8 WConv",a(4),o(8),100,72),
  "par-to-serial": mkC("par-to-serial","Par→Ser",[...Array.from({length:8},(_,i)=>`d${i}`),"clk"],["out"],110,100),
  "serial-to-par": mkC("serial-to-par","Ser→Par",["in","clk"],Array.from({length:8},(_,i)=>`q${i}`),110,100),
  "crossbar-4x4": mkC("crossbar-4x4","4×4 XBar",[...Array.from({length:4},(_,i)=>`i${i}`),...Array.from({length:8},(_,i)=>`s${i}`)],o(4),120,100),
  "arbiter-4": mkC("arbiter-4","Arbiter 4",["r0","r1","r2","r3"],["g0","g1","g2","g3"],100,72),
  "mux-tree": mkC("mux-tree","MUX Tree",[...Array.from({length:4},(_,i)=>`i${i}`),"s0","s1"],["out"],100,84),
  "sqrt-8": mkC("sqrt-8","√≈ 8",a(8),o(4),110,100),
  "cbrt-approx": mkC("cbrt-approx","∛≈",a(8),o(3),110,100),
  "factorial-4": mkC("factorial-4","Fact 4",Array.from({length:3},(_,i)=>`a${i}`),o(6),100,72),
  "gray-counter-dec": mkC("gray-counter-dec","Gray Dec",a(4),o(4),100,72),
  "thermometer-code": mkC("thermometer-code","Thermo",a(4),Array.from({length:15},(_,i)=>`o${i}`),120,140),
  "excess-3": mkC("excess-3","XS-3",a(4),o(4),100,72),

  // ====== Sequential ======
  "d-latch": {type:"d-latch",label:"D-Latch",category:"Sequential",inputs:[{id:"d",label:"D",side:"left"},{id:"en",label:"EN",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:60},
  "d-flipflop": {type:"d-flipflop",label:"D Flip-Flop",category:"Sequential",inputs:[{id:"d",label:"D",side:"left"},{id:"clk",label:"CLK",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:60},
  "t-flipflop": {type:"t-flipflop",label:"T Flip-Flop",category:"Sequential",inputs:[{id:"t",label:"T",side:"left"},{id:"clk",label:"CLK",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:60},
  "sr-latch": {type:"sr-latch",label:"SR Latch",category:"Sequential",inputs:[{id:"s",label:"S",side:"left"},{id:"r",label:"R",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:56},
  "jk-flipflop": {type:"jk-flipflop",label:"JK Flip-Flop",category:"Sequential",inputs:[{id:"j",label:"J",side:"left"},{id:"k",label:"K",side:"left"},{id:"clk",label:"CLK",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:64},
  "reg-4bit": {type:"reg-4bit",label:"4-bit Reg",category:"Sequential",inputs:["d0","d1","d2","d3","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["q0","q1","q2","q3"].map(id=>({id,label:id,side:"right" as const})),w:110,h:96},
  "d-ff-rst": {type:"d-ff-rst",label:"D-FF+RST",category:"Sequential",inputs:[{id:"d",label:"D",side:"left"},{id:"clk",label:"CLK",side:"left"},{id:"rst",label:"RST",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:64},
  "d-ff-set": {type:"d-ff-set",label:"D-FF+SET",category:"Sequential",inputs:[{id:"d",label:"D",side:"left"},{id:"clk",label:"CLK",side:"left"},{id:"set",label:"SET",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:64},
  "d-ff-rst-set": {type:"d-ff-rst-set",label:"D-FF+RS",category:"Sequential",inputs:[{id:"d",label:"D",side:"left"},{id:"clk",label:"CLK",side:"left"},{id:"rst",label:"RST",side:"left"},{id:"set",label:"SET",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:72},
  "d-ff-en": {type:"d-ff-en",label:"D-FF+EN",category:"Sequential",inputs:[{id:"d",label:"D",side:"left"},{id:"clk",label:"CLK",side:"left"},{id:"en",label:"EN",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:64},
  "d-ff-clk-en": {type:"d-ff-clk-en",label:"D-FF+CE",category:"Sequential",inputs:[{id:"d",label:"D",side:"left"},{id:"clk",label:"CLK",side:"left"},{id:"ce",label:"CE",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:64},
  "t-ff-rst": {type:"t-ff-rst",label:"T-FF+RST",category:"Sequential",inputs:[{id:"t",label:"T",side:"left"},{id:"clk",label:"CLK",side:"left"},{id:"rst",label:"RST",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:64},
  "t-ff-en": {type:"t-ff-en",label:"T-FF+EN",category:"Sequential",inputs:[{id:"t",label:"T",side:"left"},{id:"clk",label:"CLK",side:"left"},{id:"en",label:"EN",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:64},
  "jk-ff-rst": {type:"jk-ff-rst",label:"JK-FF+RST",category:"Sequential",inputs:[{id:"j",label:"J",side:"left"},{id:"k",label:"K",side:"left"},{id:"clk",label:"CLK",side:"left"},{id:"rst",label:"RST",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:72},
  "jk-ff-en": {type:"jk-ff-en",label:"JK-FF+EN",category:"Sequential",inputs:[{id:"j",label:"J",side:"left"},{id:"k",label:"K",side:"left"},{id:"clk",label:"CLK",side:"left"},{id:"en",label:"EN",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:72},
  "jk-ff-clk-en": {type:"jk-ff-clk-en",label:"JK-FF+CE",category:"Sequential",inputs:[{id:"j",label:"J",side:"left"},{id:"k",label:"K",side:"left"},{id:"clk",label:"CLK",side:"left"},{id:"ce",label:"CE",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:72},
  "sr-ff": {type:"sr-ff",label:"SR Flip-Flop",category:"Sequential",inputs:[{id:"s",label:"S",side:"left"},{id:"r",label:"R",side:"left"},{id:"clk",label:"CLK",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:64},
  "sr-ff-rst": {type:"sr-ff-rst",label:"SR-FF+RST",category:"Sequential",inputs:[{id:"s",label:"S",side:"left"},{id:"r",label:"R",side:"left"},{id:"clk",label:"CLK",side:"left"},{id:"rst",label:"RST",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:72},
  "ms-ff": {type:"ms-ff",label:"MS Flip-Flop",category:"Sequential",inputs:[{id:"d",label:"D",side:"left"},{id:"clk",label:"CLK",side:"left"}],outputs:[{id:"q",label:"Q",side:"right"},{id:"qn",label:"Q'",side:"right"}],w:90,h:60},
  "reg-8bit": mkS("reg-8bit","8-bit Reg",[...d(8),"clk","en"],q(8),120,120),
  "reg-16bit": mkS("reg-16bit","16-bit Reg",Array.from({length:16},(_,i)=>`d${i}`).concat(["clk","en"]),q(16),130,150),
  "reg-32bit": mkS("reg-32bit","32-bit Reg",Array.from({length:32},(_,i)=>`d${i}`).concat(["clk","en"]),q(32),140,200),
  "shadow-reg": mkS("shadow-reg","Shadow Reg",[...d(8),"clk","en","sh"],q(8),120,120),
  "backup-reg": mkS("backup-reg","Backup Reg",[...d(8),"clk","bk"],q(8),120,120),
  "pipeline-stage": mkS("pipeline-stage","Pipeline",[...d(8),"clk"],q(8),110,110),
  "siso-8": mkS("siso-8","SISO 8",["in","clk","en"],["out"],100,64),
  "sipo-8": mkS("sipo-8","SIPO 8",["in","clk","en"],q(8),110,100),
  "piso-8": mkS("piso-8","PISO 8",[...d(8),"clk","en","ld"],["out"],110,110),
  "pipo-8": mkS("pipo-8","PIPO 8",[...d(8),"clk"],q(8),110,110),
  "sipo-en": mkS("sipo-en","SIPO+EN",["in","clk","en"],q(8),110,100),
  "counter-up-4": mkS("counter-up-4","Up Cnt 4",["clk","en","rst"],o(4),100,72),
  "counter-down-4": mkS("counter-down-4","Dn Cnt 4",["clk","en","rst"],o(4),100,72),
  "counter-updown-4": mkS("counter-updown-4","UD Cnt 4",["clk","en","up","rst"],o(4),100,80),
  "counter-up-8": mkS("counter-up-8","Up Cnt 8",["clk","en","rst"],o(8),110,100),
  "counter-mod10": mkS("counter-mod10","Mod-10",["clk","en"],o(4),100,72),
  "counter-mod6": mkS("counter-mod6","Mod-6",["clk","en"],o(3),90,64),
  "counter-mod12": mkS("counter-mod12","Mod-12",["clk","en"],o(4),100,72),
  "counter-mod16": mkS("counter-mod16","Mod-16",["clk","en"],o(4),100,72),
  "counter-load-4": mkS("counter-load-4","Cnt+Load",[...d(4),"clk","en","ld"],o(4),110,84),
  "counter-en-4": mkS("counter-en-4","Cnt+EN 4",["clk","en","rst"],o(4),100,72),
  "johnson-4": mkS("johnson-4","Johnson 4",["clk","en"],o(4),100,72),
  "ring-4": mkS("ring-4","Ring 4",["clk","en"],o(4),100,72),
  "johnson-8": mkS("johnson-8","Johnson 8",["clk","en"],o(8),110,100),
  "ring-8": mkS("ring-8","Ring 8",["clk","en"],o(8),110,100),
  "lfsr-8": mkS("lfsr-8","LFSR 8",["clk","en","rst"],o(8),110,100),
  "lfsr-16": mkS("lfsr-16","LFSR 16",["clk","en","rst"],Array.from({length:16},(_,i)=>`q${i}`),120,130),
  "lfsr-max-8": mkS("lfsr-max-8","Max LFSR",["clk","en","rst"],o(8),110,100),
  "freq-div-2": mkS("freq-div-2","÷2",["clk"],["out"],80,48),
  "freq-div-4": mkS("freq-div-4","÷4",["clk"],o(2),80,56),
  "freq-div-8": mkS("freq-div-8","÷8",["clk"],o(3),80,64),
  "freq-div-10": mkS("freq-div-10","÷10",["clk"],o(4),90,72),
  "one-shot": mkS("one-shot","One-Shot",["in","clk"],["out"],80,48),
  "retriggerable-one-shot": mkS("retriggerable-one-shot","Retrigger",["in","clk"],["out"],80,48),
  "debounce": mkS("debounce","Debounce",["in","clk"],["out"],80,48),
  "pulse-stretcher": mkS("pulse-stretcher","Pulse Str",["in","clk"],["out"],80,48),
  "delay-1": mkS("delay-1","Delay 1",["in","clk"],["out"],80,48),
  "delay-4": mkS("delay-4","Delay 4",["in","clk"],o(4),100,72),
  "delay-8": mkS("delay-8","Delay 8",["in","clk"],o(8),110,100),
  "sync-2ff": mkS("sync-2ff","Sync 2FF",["in","clk"],["out"],80,48),
  "sync-3ff": mkS("sync-3ff","Sync 3FF",["in","clk"],["out"],80,48),
  "edge-det-rising-seq": mkS("edge-det-rising-seq","Rise Det",["in","clk"],["out"],80,48),
  "edge-det-falling-seq": mkS("edge-det-falling-seq","Fall Det",["in","clk"],["out"],80,48),
  "fifo-4": mkS("fifo-4","FIFO 4",["in0","in1","in2","in3","clk","wr","rd"],["out0","out1","out2","out3","full","empty"],120,112),
  "fifo-8": mkS("fifo-8","FIFO 8",Array.from({length:8},(_,i)=>`in${i}`).concat(["clk","wr","rd"]),Array.from({length:8},(_,i)=>`out${i}`).concat(["full","empty"]),130,130),
  "stack-4": mkS("stack-4","Stack 4",["in0","in1","in2","in3","clk","push","pop"],["out0","out1","out2","out3","full","empty"],120,112),
  "circ-buf-4": mkS("circ-buf-4","Circ Buf",["in0","in1","in2","in3","clk","wr"],["out0","out1","out2","out3","full"],120,100),
  "fsm-4": mkS("fsm-4","4-State FSM",["in0","in1","clk","rst"],["out0","out1","s0","s1"],110,84),
  "seq-det-101": mkS("seq-det-101","Seq 101",["in","clk"],["out"],80,48),
  "seq-det-1101": mkS("seq-det-1101","Seq 1101",["in","clk"],["out"],80,48),
  "parity-fsm": mkS("parity-fsm","Parity FSM",["in","clk"],["even","odd"],80,56),
  "traffic-ctrl": mkS("traffic-ctrl","Traffic Ctrl",["s0","s1","s2","clk"],["r1","y1","g1","r2","y2","g2"],120,112),
  "vending-ctrl": mkS("vending-ctrl","Vending",["in0","in1","in2","clk","rst"],["out0","out1","change"],110,84),
  "bus-arbiter-seq": mkS("bus-arbiter-seq","Bus Arb",["r0","r1","r2","r3","clk"],["g0","g1","g2","g3"],100,80),
  "bus-arbiter-pri": mkS("bus-arbiter-pri","Pri Arb",["r0","r1","r2","r3","clk"],["g0","g1","g2","g3"],100,80),
  "handshake-init": mkS("handshake-init","HS Init",["data0","data1","data2","data3","clk","req"],["ack","valid"],110,84),
  "handshake-resp": mkS("handshake-resp","HS Resp",["in0","in1","in2","in3","clk","req"],["out0","out1","out2","out3","ack"],110,84),
  "clk-div-prog": mkS("clk-div-prog","Clk Div",["clk","n0","n1","n2","n3"],["out"],100,72),
  "timer-4": mkS("timer-4","Timer 4",["clk","en","rst"],o(4),100,72),
  "stopwatch-ctrl": mkS("stopwatch-ctrl","Stopwatch",["clk","start","reset"],["d0","d1","d2","d3","running"],110,84),
  "ram-4x4": mkS("ram-4x4","RAM 4×4",["a0","a1","d0","d1","d2","d3","clk","wr"],["q0","q1","q2","q3"],110,96),
  "rom-8x4": mkS("rom-8x4","ROM 8×4",["a0","a1","a2"],o(4),90,64),
  "rom-16x8": mkS("rom-16x8","ROM 16×8",Array.from({length:4},(_,i)=>`a${i}`),o(8),110,84),
  "ram-rd-port": mkS("ram-rd-port","RAM Read",["a0","a1","clk"],o(4),90,64),
  "ram-wr-port": mkS("ram-wr-port","RAM Write",["a0","a1","d0","d1","d2","d3","clk","en"],["done"],110,84),
  "reg-file-4x4": mkS("reg-file-4x4","RegFile 4×4",["ra0","ra1","wa0","wa1","wd0","wd1","wd2","wd3","clk","wr"],["rd0","rd1","rd2","rd3"],120,112),
  "reg-file-8x8": mkS("reg-file-8x8","RegFile 8×8",["ra0","ra1","ra2","wa0","wa1","wa2",...Array.from({length:8},(_,i)=>`wd${i}`),"clk","wr"],Array.from({length:8},(_,i)=>`rd${i}`),130,130),
  "state-mem": mkS("state-mem","State Mem",["s0","s1","clk","rst"],["ns0","ns1"],90,64),
  "history-reg": mkS("history-reg","History Reg",["in0","in1","in2","in3","clk"],Array.from({length:16},(_,i)=>`h${i}`),120,100),
  "hazard-flush": mkS("hazard-flush","Hazard Flush",["branch","clk"],["flush"],80,48),
  "exception-reg": mkS("exception-reg","Exc Reg",["e0","e1","e2","e3","clk","en"],["q0","q1","q2","q3"],100,80),
  "interrupt-reg": mkS("interrupt-reg","IRQ Reg",["i0","i1","i2","i3","clk","en"],["q0","q1","q2","q3","pending"],110,84),
  "context-save": mkS("context-save","Ctx Save",["d0","d1","d2","d3","clk","save"],Array.from({length:4},(_,i)=>`q${i}`),100,80),
  "context-restore": mkS("context-restore","Ctx Rstr",["d0","d1","d2","d3","clk","rstr"],Array.from({length:4},(_,i)=>`q${i}`),100,80),
  "branch-predict": mkS("branch-predict","Br Pred",["pc0","pc1","pc2","pc3","taken","clk"],["target0","target1","target2","target3","predict"],120,84),
  "return-stack": mkS("return-stack","Ret Stack",["in0","in1","in2","in3","clk","push","pop"],["out0","out1","out2","out3"],110,84),
  "icache-lookup": mkS("icache-lookup","I-Cache",["a0","a1","a2","a3","clk"],["d0","d1","d2","d3","hit"],110,84),
  "dtlb-entry": mkS("dtlb-entry","DTLB",["v0","v1","v2","v3","clk"],["p0","p1","p2","p3","valid"],110,84),
  "page-table-entry": mkS("page-table-entry","PTE",["v0","v1","v2","v3","clk"],["p0","p1","p2","p3","dirty","valid"],110,92),
  "uart-tx": mkS("uart-tx","UART TX",["d0","d1","d2","d3","d4","d5","d6","d7","clk","start"],["tx","busy"],120,100),
  "uart-rx": mkS("uart-rx","UART RX",["rx","clk"],["d0","d1","d2","d3","d4","d5","d6","d7","ready"],120,100),
  "bitbang-tx": mkS("bitbang-tx","BB TX",["in","clk","en"],["out"],80,48),
  "bitbang-rx": mkS("bitbang-rx","BB RX",["in","clk","en"],["out","valid"],80,56),
  "spi-master": mkS("spi-master","SPI Master",["d0","d1","d2","d3","clk","ss"],["mosi","sclk","busy"],110,84),
  "spi-slave": mkS("spi-slave","SPI Slave",["mosi","sclk","ss","clk"],["d0","d1","d2","d3","valid"],110,84),
  "i2c-master": mkS("i2c-master","I2C Master",["d0","d1","d2","d3","clk","start"],["sda","scl","busy"],110,84),
  "i2c-slave": mkS("i2c-slave","I2C Slave",["sda","scl","clk"],["d0","d1","d2","d3","ack"],110,84),

  // ====== Communication ======
  "clk-recovery": mkS("clk-recovery","Clk Recov",["in","ref_clk"],["recovered_clk"],80,56),
  "baud-gen": mkS("baud-gen","Baud Gen",["clk","b0","b1","b2","b3"],["tx_clk","rx_clk"],100,72),
  "tx-mux": mkS("tx-mux","TX Mux",["d0","d1","sel","clk"],["out"],80,56),
  "rx-demux": mkS("rx-demux","RX Demux",["in","sel","clk"],["o0","o1"],80,56),
  "scrambler": mkS("scrambler","Scrambler",["in","clk"],["out"],80,48),
  "descrambler": mkS("descrambler","Descramble",["in","clk"],["out"],80,48),
  "manchester-enc": mkS("manchester-enc","Manch Enc",["in","clk"],["out"],80,48),
  "manchester-dec": mkS("manchester-dec","Manch Dec",["in","clk"],["out","valid"],80,56),
  "nrz-enc": mkS("nrz-enc","NRZ Enc",["in","clk"],["out"],80,48),
  "nrz-dec": mkS("nrz-dec","NRZ Dec",["in","clk"],["out"],80,48),
  "pipeline-reg-stage": mkS("pipeline-reg-stage","Pipe Stage",Array.from({length:8},(_,i)=>`d${i}`).concat(["clk"]),q(8),110,100),

  // ====== Signal Processing ======
  "hazard-filter": mkS("hazard-filter","Hazard Filt",["in","clk"],["out"],80,48),
  "glitch-det": mkS("glitch-det","Glitch Det",["in","clk"],["out","glitch"],80,56),
  "metastab-filter": mkS("metastab-filter","Meta Filt",["in","clk"],["out"],80,48),
  "clk-gate": mkS("clk-gate","Clk Gate",["clk","en"],["gated_clk"],80,48),
  "io-pad": mkS("io-pad","I/O Pad",["in","en","oe"],["out","pad"],80,56),
  "level-shift": mkS("level-shift","Level Shift",["in"],["out"],70,44),
  "schmitt-trigger": mkS("schmitt-trigger","Schmitt",["in"],["out"],70,44),
  "sample-hold": mkS("sample-hold","S&H",["in","clk","en"],["out"],80,56),
  "peak-det": mkS("peak-det","Peak Det",["in","clk"],["out","peak"],80,56),
  "zero-cross": mkS("zero-cross","Zero Xing",["in"],["out"],70,44),
  "phase-det": mkS("phase-det","Phase Det",["a","b"],["up","dn"],80,56),
  "charge-pump": mkS("charge-pump","Chg Pump",["up","dn"],["out"],80,48),
  "digital-pot": mkS("digital-pot","Digi Pot",["w0","w1","w2","w3","en"],["r0","r1","r2","r3"],100,72),

  // ====== Bus/Interface ======
  "data-mux": mkS("data-mux","Data Mux",["d0","d1","d2","d3","s0","s1"],["out0","out1","out2","out3"],100,80),
  "addr-decode": mkS("addr-decode","Addr Dec",["a0","a1","a2","a3"],["cs0","cs1","cs2","cs3"],100,72),
  "wait-state-gen": mkS("wait-state-gen","Wait Gen",["ready","clk"],["wait","ws0","ws1"],80,64),
  "bus-driver": mkS("bus-driver","Bus Driver",Array.from({length:8},(_,i)=>`d${i}`).concat(["en"]),Array.from({length:8},(_,i)=>`q${i}`),110,100),
  "bus-transceiver": mkS("bus-transceiver","Bus Xcvr",Array.from({length:8},(_,i)=>`a${i}`).concat(["dir","en"]),Array.from({length:8},(_,i)=>`b${i}`),120,110),
  "bus-buffer": mkS("bus-buffer","Bus Buffer",Array.from({length:8},(_,i)=>`d${i}`).concat(["en"]),Array.from({length:8},(_,i)=>`q${i}`),110,100),
  "bus-holder": mkS("bus-holder","Bus Hold",Array.from({length:8},(_,i)=>`d${i}`).concat(["en"]),Array.from({length:8},(_,i)=>`q${i}`),110,100),
  "tri-state-bus": mkS("tri-state-bus","TS Bus",Array.from({length:8},(_,i)=>`d${i}`).concat(["en"]),Array.from({length:8},(_,i)=>`q${i}`),110,100),
  "dma-controller": mkS("dma-controller","DMA Ctrl",["req","ack","clk"],["done","addr0","addr1","addr2","addr3"],110,84),
  "bus-bridge": mkS("bus-bridge","Bus Bridge",Array.from({length:8},(_,i)=>`a${i}`).concat(["clk","en"]),Array.from({length:8},(_,i)=>`b${i}`),120,110),

  // ====== Memory Systems ======
  "clock-domain-crossing": mkS("clock-domain-crossing","CDC",["in","clk1","clk2"],["out"],80,56),
  "async-fifo": mkS("async-fifo","Async FIFO",Array.from({length:8},(_,i)=>`d${i}`).concat(["wr_clk","rd_clk","wr","rd"]),Array.from({length:8},(_,i)=>`q${i}`).concat(["full","empty"]),130,130),
  "dual-port-ram": mkS("dual-port-ram","DP RAM",["a0","a1","wd0","wd1","wd2","wd3","wr_clk","rd_clk","wr"],["rd0","rd1","rd2","rd3"],120,112),
  "multi-port-reg": mkS("multi-port-reg","MP Reg",["d0","d1","d2","d3","clk","en0","en1"],["q0","q1","q2","q3"],100,84),
  "shared-reg": mkS("shared-reg","Shared Reg",["d0","d1","d2","d3","clk","en"],["q0","q1","q2","q3"],100,80),
  "atomic-reg": mkS("atomic-reg","Atomic Reg",["d0","d1","d2","d3","clk","lock"],["q0","q1","q2","q3","done"],110,84),
  "lock-free-queue": mkS("lock-free-queue","LF Queue",["in0","in1","in2","in3","clk","en"],["out0","out1","out2","out3","full","empty"],120,112),
  "message-fifo": mkS("message-fifo","Msg FIFO",["m0","m1","m2","m3","clk","wr","rd"],["q0","q1","q2","q3","full","empty"],120,112),
  "event-queue": mkS("event-queue","Evt Queue",["e0","e1","e2","clk","wr","rd"],["q0","q1","q2","full","empty"],110,96),

  // ====== Advanced ======
  "interrupt-controller": mkS("interrupt-controller","IRQ Ctrl",["i0","i1","i2","i3","clk","en"],["irq","a0","a1"],110,84),
  "dma-channel": mkS("dma-channel","DMA Ch",["req","ack","clk"],["done"],80,48),
  "bus-monitor": mkS("bus-monitor","Bus Mon",Array.from({length:8},(_,i)=>`d${i}`).concat(["clk","en"]),["err","valid"],110,100),
  "protocol-decoder": mkS("protocol-decoder","Proto Dec",["in","clk"],["d0","d1","d2","d3","valid"],100,80),
  "bit-time-gen": mkS("bit-time-gen","Bit Time",["clk","b0","b1","b2","b3"],["bit_clk"],100,72),
  "frame-gen": mkS("frame-gen","Frame Gen",["d0","d1","d2","d3","clk","start"],["tx","busy"],100,80),
  "frame-check": mkS("frame-check","Frame Chk",["d0","d1","d2","d3","clk"],["ok","valid"],100,72),
  "reorder-buffer": mkS("reorder-buffer","Reorder Buf",["in0","in1","in2","in3","clk","en"],["out0","out1","out2","out3"],120,84),
  "reservation-station": mkS("reservation-station","Res Stn",["a","b","op0","op1","clk","en"],["q","valid"],110,84),
  "load-store-queue": mkS("load-store-queue","LS Queue",["addr0","addr1","data0","data1","clk","wr","rd"],["out0","out1","full","empty"],120,100),
  "prefetch-buffer": mkS("prefetch-buffer","Prefetch",["a0","a1","a2","a3","clk"],["d0","d1","d2","d3","valid"],110,84),
  "cache-valid-bit": mkS("cache-valid-bit","Cache Valid",["a0","a1","clk","en"],["hit"],90,64),

  // ====== Sensors ======
  "temp-sensor": {type:"temp-sensor",label:"Temp Sensor",category:"Sensors",inputs:[],outputs:["d0","d1","d2","d3","d4","d5","d6","d7"].map(id=>({id,label:id,side:"right" as const})),w:80,h:70},
  "humidity-sensor": {type:"humidity-sensor",label:"Humidity",category:"Sensors",inputs:[],outputs:["d0","d1","d2","d3","d4","d5","d6","d7"].map(id=>({id,label:id,side:"right" as const})),w:80,h:70},
  "pressure-sensor": {type:"pressure-sensor",label:"Pressure",category:"Sensors",inputs:[],outputs:["d0","d1","d2","d3","d4","d5","d6","d7"].map(id=>({id,label:id,side:"right" as const})),w:80,h:70},
  "light-sensor": {type:"light-sensor",label:"Light/LDR",category:"Sensors",inputs:[],outputs:["d0","d1","d2","d3","d4","d5","d6","d7"].map(id=>({id,label:id,side:"right" as const})),w:80,h:70},
  "ir-sensor": mkIn("ir-sensor","IR Sensor",["out"],70,44),
  "ultrasonic-sensor": {type:"ultrasonic-sensor",label:"Ultrasonic",category:"Sensors",inputs:[],outputs:["d0","d1","d2","d3","d4","d5","d6","d7"].map(id=>({id,label:id,side:"right" as const})),w:80,h:70},
  "motion-sensor": mkIn("motion-sensor","PIR Motion",["out"],70,44),
  "accelerometer-sensor": {type:"accelerometer-sensor",label:"Accel 3-Ax",category:"Sensors",inputs:[],outputs:["x0","x1","x2","x3","y0","y1","y2","y3","z0","z1","z2","z3"].map(id=>({id,label:id,side:"right" as const})),w:90,h:100},
  "gyro-sensor": {type:"gyro-sensor",label:"Gyro 3-Ax",category:"Sensors",inputs:[],outputs:["x0","x1","x2","x3","y0","y1","y2","y3","z0","z1","z2","z3"].map(id=>({id,label:id,side:"right" as const})),w:90,h:100},
  "magnetic-sensor": mkIn("magnetic-sensor","Hall Mag",["out"],70,44),
  "force-sensor": {type:"force-sensor",label:"Force FSR",category:"Sensors",inputs:[],outputs:["d0","d1","d2","d3","d4","d5","d6","d7"].map(id=>({id,label:id,side:"right" as const})),w:80,h:70},
  "proximity-sensor": mkIn("proximity-sensor","Proximity",["out"],70,44),
  "hall-sensor": mkIn("hall-sensor","Hall Effect",["out"],70,44),
  "gas-sensor": {type:"gas-sensor",label:"Gas Sensor",category:"Sensors",inputs:[],outputs:["d0","d1","d2","d3","d4","d5","d6","d7"].map(id=>({id,label:id,side:"right" as const})),w:80,h:70},
  "camera-sensor": {type:"camera-sensor",label:"Camera",category:"Sensors",inputs:["clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["d0","d1","d2","d3","d4","d5","d6","d7","valid"].map(id=>({id,label:id,side:"right" as const})),w:90,h:80},
  "microphone-sensor": {type:"microphone-sensor",label:"Microphone",category:"Sensors",inputs:[],outputs:["d0","d1","d2","d3","d4","d5","d6","d7"].map(id=>({id,label:id,side:"right" as const})),w:80,h:70},
  "gps-module": {type:"gps-module",label:"GPS Module",category:"Sensors",inputs:[],outputs:["d0","d1","d2","d3","d4","d5","d6","d7","fix"].map(id=>({id,label:id,side:"right" as const})),w:90,h:80},
  "rfid-reader": {type:"rfid-reader",label:"RFID Read",category:"Sensors",inputs:["en"].map(id=>({id,label:id,side:"left" as const})),outputs:["d0","d1","d2","d3","d4","d5","d6","d7","valid"].map(id=>({id,label:id,side:"right" as const})),w:90,h:80},
  "nfc-reader": {type:"nfc-reader",label:"NFC Reader",category:"Sensors",inputs:["en"].map(id=>({id,label:id,side:"left" as const})),outputs:["d0","d1","d2","d3","d4","d5","d6","d7","valid"].map(id=>({id,label:id,side:"right" as const})),w:90,h:80},
  "barcode-scanner": {type:"barcode-scanner",label:"Barcode",category:"Sensors",inputs:["en"].map(id=>({id,label:id,side:"left" as const})),outputs:["d0","d1","d2","d3","d4","d5","d6","d7","valid"].map(id=>({id,label:id,side:"right" as const})),w:90,h:80},
  "fingerprint-sensor": {type:"fingerprint-sensor",label:"Fingerprint",category:"Sensors",inputs:["en"].map(id=>({id,label:id,side:"left" as const})),outputs:["match","d0","d1","d2","d3"].map(id=>({id,label:id,side:"right" as const})),w:90,h:70},
  "face-recog-cam": {type:"face-recog-cam",label:"Face Recog",category:"Sensors",inputs:["clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["match","d0","d1","d2","d3"].map(id=>({id,label:id,side:"right" as const})),w:90,h:70},

  // ====== Processors ======
  "microcontroller": {type:"microcontroller",label:"MCU",category:"Processors",inputs:["d0","d1","d2","d3","d4","d5","d6","d7","clk","rst","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["d0","d1","d2","d3","d4","d5","d6","d7","tx","rx"].map(id=>({id,label:id,side:"right" as const})),w:110,h:110},
  "cpu-block": {type:"cpu-block",label:"CPU",category:"Processors",inputs:["d0","d1","d2","d3","d4","d5","d6","d7","clk","rst","irq"].map(id=>({id,label:id,side:"left" as const})),outputs:["d0","d1","d2","d3","d4","d5","d6","d7","a0","a1","a2","a3","wr","rd"].map(id=>({id,label:id,side:"right" as const})),w:120,h:130},
  "fpga-block": {type:"fpga-block",label:"FPGA",category:"Processors",inputs:["d0","d1","d2","d3","d4","d5","d6","d7","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["d0","d1","d2","d3","d4","d5","d6","d7"].map(id=>({id,label:id,side:"right" as const})),w:100,h:90},
  "dsp-block": {type:"dsp-block",label:"DSP",category:"Processors",inputs:["d0","d1","d2","d3","d4","d5","d6","d7","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["o0","o1","o2","o3","o4","o5","o6","o7"].map(id=>({id,label:id,side:"right" as const})),w:100,h:90},
  "npu-block": {type:"npu-block",label:"NPU/TPU",category:"Processors",inputs:["d0","d1","d2","d3","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["o0","o1","o2","o3","done"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},

  // ====== Memory Blocks ======
  "ram-block": {type:"ram-block",label:"RAM",category:"Memory",inputs:["a0","a1","a2","a3","d0","d1","d2","d3","clk","wr"].map(id=>({id,label:id,side:"left" as const})),outputs:["q0","q1","q2","q3"].map(id=>({id,label:id,side:"right" as const})),w:100,h:90},
  "rom-block": {type:"rom-block",label:"ROM",category:"Memory",inputs:["a0","a1","a2","a3"].map(id=>({id,label:id,side:"left" as const})),outputs:["d0","d1","d2","d3"].map(id=>({id,label:id,side:"right" as const})),w:90,h:70},
  "eeprom-block": {type:"eeprom-block",label:"EEPROM",category:"Memory",inputs:["a0","a1","a2","a3","d0","d1","d2","d3","clk","wr"].map(id=>({id,label:id,side:"left" as const})),outputs:["q0","q1","q2","q3"].map(id=>({id,label:id,side:"right" as const})),w:100,h:90},
  "flash-block": {type:"flash-block",label:"Flash",category:"Memory",inputs:["a0","a1","a2","a3","d0","d1","d2","d3","clk","wr"].map(id=>({id,label:id,side:"left" as const})),outputs:["q0","q1","q2","q3","done"].map(id=>({id,label:id,side:"right" as const})),w:100,h:90},
  "sram-block": {type:"sram-block",label:"SRAM",category:"Memory",inputs:["a0","a1","a2","a3","d0","d1","d2","d3","wr","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["q0","q1","q2","q3"].map(id=>({id,label:id,side:"right" as const})),w:100,h:90},
  "cache-block": {type:"cache-block",label:"Cache",category:"Memory",inputs:["a0","a1","a2","a3","d0","d1","d2","d3","clk","wr"].map(id=>({id,label:id,side:"left" as const})),outputs:["q0","q1","q2","q3","hit"].map(id=>({id,label:id,side:"right" as const})),w:100,h:90},

  // ====== Communication Blocks ======
  "uart-block": {type:"uart-block",label:"UART",category:"Communication",inputs:["d0","d1","d2","d3","d4","d5","d6","d7","clk","start"].map(id=>({id,label:id,side:"left" as const})),outputs:["tx","busy"].map(id=>({id,label:id,side:"right" as const})),w:100,h:90},
  "spi-block": {type:"spi-block",label:"SPI",category:"Communication",inputs:["d0","d1","d2","d3","clk","ss"].map(id=>({id,label:id,side:"left" as const})),outputs:["mosi","sclk","busy"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "i2c-block": {type:"i2c-block",label:"I2C",category:"Communication",inputs:["d0","d1","d2","d3","clk","start"].map(id=>({id,label:id,side:"left" as const})),outputs:["sda","scl","busy"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "can-bus": {type:"can-bus",label:"CAN Bus",category:"Communication",inputs:["d0","d1","d2","d3","d4","d5","d6","d7","clk"].map(id=>({id,label:id,side:"left" as const})),outputs:["tx","ack","busy"].map(id=>({id,label:id,side:"right" as const})),w:100,h:90},
  "usb-block": {type:"usb-block",label:"USB",category:"Communication",inputs:["d0","d1","d2","d3","d4","d5","d6","d7","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["dp","dm","busy"].map(id=>({id,label:id,side:"right" as const})),w:100,h:90},
  "ethernet-block": {type:"ethernet-block",label:"Ethernet",category:"Communication",inputs:["d0","d1","d2","d3","d4","d5","d6","d7","clk"].map(id=>({id,label:id,side:"left" as const})),outputs:["tx0","tx1","tx2","tx3","rx0","rx1","rx2","rx3"].map(id=>({id,label:id,side:"right" as const})),w:110,h:100},
  "wifi-block": {type:"wifi-block",label:"WiFi",category:"Communication",inputs:["d0","d1","d2","d3","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["tx","rx","connected"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "bluetooth-block": {type:"bluetooth-block",label:"Bluetooth",category:"Communication",inputs:["d0","d1","d2","d3","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["tx","rx","connected"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "zigbee-block": {type:"zigbee-block",label:"Zigbee",category:"Communication",inputs:["d0","d1","d2","d3","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["tx","rx","connected"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "lora-block": {type:"lora-block",label:"LoRa",category:"Communication",inputs:["d0","d1","d2","d3","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["tx","rx","connected"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "gsm-module": {type:"gsm-module",label:"GSM/4G/5G",category:"Communication",inputs:["d0","d1","d2","d3","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["tx","rx","connected"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "mqtt-block": {type:"mqtt-block",label:"MQTT",category:"Communication",inputs:["d0","d1","d2","d3","topic0","topic1","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["tx","rx","connected"].map(id=>({id,label:id,side:"right" as const})),w:110,h:90},

  // ====== Power ======
  "battery": {type:"battery",label:"Battery",category:"Power",inputs:[],outputs:["vcc","gnd"].map(id=>({id,label:id,side:"right" as const})),w:70,h:60},
  "adapter": {type:"adapter",label:"Adapter",category:"Power",inputs:[],outputs:["vcc","gnd"].map(id=>({id,label:id,side:"right" as const})),w:70,h:60},
  "voltage-regulator": {type:"voltage-regulator",label:"V Reg",category:"Power",inputs:["vin","gnd"].map(id=>({id,label:id,side:"left" as const})),outputs:["vout","gnd"].map(id=>({id,label:id,side:"right" as const})),w:80,h:60},
  "fuse": {type:"fuse",label:"Fuse",category:"Power",inputs:["in"].map(id=>({id,label:id,side:"left" as const})),outputs:["out"].map(id=>({id,label:id,side:"right" as const})),w:70,h:44},
  "buck-converter": {type:"buck-converter",label:"Buck Conv",category:"Power",inputs:["vin","clk"].map(id=>({id,label:id,side:"left" as const})),outputs:["vout"].map(id=>({id,label:id,side:"right" as const})),w:80,h:56},
  "boost-converter": {type:"boost-converter",label:"Boost Conv",category:"Power",inputs:["vin","clk"].map(id=>({id,label:id,side:"left" as const})),outputs:["vout"].map(id=>({id,label:id,side:"right" as const})),w:80,h:56},
  "bms": {type:"bms",label:"BMS",category:"Power",inputs:["vin","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["vout","fault"].map(id=>({id,label:id,side:"right" as const})),w:80,h:56},
  "power-switch": {type:"power-switch",label:"Pwr Switch",category:"Power",inputs:["in","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["out"].map(id=>({id,label:id,side:"right" as const})),w:80,h:48},

  // ====== Electronic Components ======
  "resistor": {type:"resistor",label:"Resistor",category:"Electronic",inputs:["a"].map(id=>({id,label:id,side:"left" as const})),outputs:["b"].map(id=>({id,label:id,side:"right" as const})),w:70,h:40},
  "capacitor": {type:"capacitor",label:"Capacitor",category:"Electronic",inputs:["a"].map(id=>({id,label:id,side:"left" as const})),outputs:["b"].map(id=>({id,label:id,side:"right" as const})),w:70,h:40},
  "inductor": {type:"inductor",label:"Inductor",category:"Electronic",inputs:["a"].map(id=>({id,label:id,side:"left" as const})),outputs:["b"].map(id=>({id,label:id,side:"right" as const})),w:70,h:40},
  "diode": {type:"diode",label:"Diode",category:"Electronic",inputs:["a"].map(id=>({id,label:id,side:"left" as const})),outputs:["b"].map(id=>({id,label:id,side:"right" as const})),w:70,h:40},
  "zener-diode": {type:"zener-diode",label:"Zener",category:"Electronic",inputs:["a"].map(id=>({id,label:id,side:"left" as const})),outputs:["b"].map(id=>({id,label:id,side:"right" as const})),w:70,h:40},
  "transistor-bjt": {type:"transistor-bjt",label:"BJT NPN",category:"Electronic",inputs:["b","c"].map(id=>({id,label:id,side:"left" as const})),outputs:["e"].map(id=>({id,label:id,side:"right" as const})),w:70,h:56},
  "transistor-mosfet": {type:"transistor-mosfet",label:"MOSFET",category:"Electronic",inputs:["g","d"].map(id=>({id,label:id,side:"left" as const})),outputs:["s"].map(id=>({id,label:id,side:"right" as const})),w:70,h:56},
  "op-amp": {type:"op-amp",label:"Op-Amp",category:"Electronic",inputs:["inp","inn","vcc","vss"].map(id=>({id,label:id,side:"left" as const})),outputs:["outp","outn"].map(id=>({id,label:id,side:"right" as const})),w:80,h:70},
  "crystal-osc": {type:"crystal-osc",label:"XTAL OSC",category:"Electronic",inputs:[],outputs:["out"].map(id=>({id,label:id,side:"right" as const})),w:70,h:50},
  "transformer": {type:"transformer",label:"Transformer",category:"Electronic",inputs:["a","b"].map(id=>({id,label:id,side:"left" as const})),outputs:["c","d"].map(id=>({id,label:id,side:"right" as const})),w:80,h:60},

  // ====== Actuators ======
  "dc-motor": {type:"dc-motor",label:"DC Motor",category:"Actuators",inputs:["in1","in2"].map(id=>({id,label:id,side:"left" as const})),outputs:["sense"].map(id=>({id,label:id,side:"right" as const})),w:80,h:64},
  "relay": {type:"relay",label:"Relay",category:"Actuators",inputs:["coil"].map(id=>({id,label:id,side:"left" as const})),outputs:["com","no","nc"].map(id=>({id,label:id,side:"right" as const})),w:80,h:64},
  "solenoid": {type:"solenoid",label:"Solenoid",category:"Actuators",inputs:["in"].map(id=>({id,label:id,side:"left" as const})),outputs:["out"].map(id=>({id,label:id,side:"right" as const})),w:70,h:48},
  "oled-display": {type:"oled-display",label:"OLED",category:"Actuators",inputs:["d0","d1","d2","d3","d4","d5","d6","d7","clk"].map(id=>({id,label:id,side:"left" as const})),outputs:[].map(id=>({id,label:id,side:"right" as const})),w:90,h:80},
  "speaker": {type:"speaker",label:"Speaker",category:"Actuators",inputs:["in"].map(id=>({id,label:id,side:"left" as const})),outputs:[].map(id=>({id,label:id,side:"right" as const})),w:70,h:56},
  "linear-actuator": {type:"linear-actuator",label:"Lin Act",category:"Actuators",inputs:["in1","in2"].map(id=>({id,label:id,side:"left" as const})),outputs:["pos"].map(id=>({id,label:id,side:"right" as const})),w:80,h:56},
  "robotic-arm": {type:"robotic-arm",label:"Robo Arm",category:"Actuators",inputs:["d0","d1","d2","d3","d4","d5","clk"].map(id=>({id,label:id,side:"left" as const})),outputs:["done"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "printer-out": {type:"printer-out",label:"Printer",category:"Actuators",inputs:["d0","d1","d2","d3","d4","d5","d6","d7","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["busy"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},

  // ====== Boards ======
  "arduino-uno": {type:"arduino-uno",label:"Arduino Uno",category:"Boards",inputs:["d0","d1","d2","d3","d4","d5","d6","d7","clk","rst"].map(id=>({id,label:id,side:"left" as const})),outputs:["d0","d1","d2","d3","d4","d5","d6","d7","tx","rx","pwm0","pwm1"].map(id=>({id,label:id,side:"right" as const})),w:120,h:120},
  "arduino-nano": {type:"arduino-nano",label:"Arduino Nano",category:"Boards",inputs:["d0","d1","d2","d3","d4","d5","d6","d7","clk","rst"].map(id=>({id,label:id,side:"left" as const})),outputs:["d0","d1","d2","d3","d4","d5","d6","d7","tx","rx","pwm0","pwm1"].map(id=>({id,label:id,side:"right" as const})),w:110,h:110},
  "raspberry-pi": {type:"raspberry-pi",label:"Raspberry Pi",category:"Boards",inputs:["gpio0","gpio1","gpio2","gpio3","gpio4","gpio5","clk","rst"].map(id=>({id,label:id,side:"left" as const})),outputs:["gpio0","gpio1","gpio2","gpio3","gpio4","gpio5","sda","scl","tx","rx"].map(id=>({id,label:id,side:"right" as const})),w:120,h:110},
  "raspberry-pi-pico": {type:"raspberry-pi-pico",label:"RPi Pico",category:"Boards",inputs:["gp0","gp1","gp2","gp3","gp4","gp5","clk","rst"].map(id=>({id,label:id,side:"left" as const})),outputs:["gp0","gp1","gp2","gp3","gp4","gp5","tx","rx","pwm0","pwm1"].map(id=>({id,label:id,side:"right" as const})),w:110,h:100},
  "esp32": {type:"esp32",label:"ESP32",category:"Boards",inputs:["gpio0","gpio1","gpio2","gpio3","gpio4","gpio5","gpio6","gpio7","clk","rst"].map(id=>({id,label:id,side:"left" as const})),outputs:["gpio0","gpio1","gpio2","gpio3","gpio4","gpio5","tx","rx","adc0","adc1","wifi"].map(id=>({id,label:id,side:"right" as const})),w:120,h:120},
  "stm32": {type:"stm32",label:"STM32F103",category:"Boards",inputs:["pa0","pa1","pa2","pa3","pb0","pb1","clk","rst","boot0"].map(id=>({id,label:id,side:"left" as const})),outputs:["pa0","pa1","pa2","pa3","pb0","pb1","tx","rx","adc0","adc1","can"].map(id=>({id,label:id,side:"right" as const})),w:120,h:120},

  // ====== Advanced Processors ======
  "gpu-block": {type:"gpu-block",label:"GPU",category:"Processors",inputs:["d0","d1","d2","d3","d4","d5","d6","d7","clk","en","rst"].map(id=>({id,label:id,side:"left" as const})),outputs:["o0","o1","o2","o3","o4","o5","o6","o7","done"].map(id=>({id,label:id,side:"right" as const})),w:120,h:110},

  // ====== Advanced Sensors ======
  "bme280": {type:"bme280",label:"BME280",category:"Sensors",inputs:["en"].map(id=>({id,label:id,side:"left" as const})),outputs:["t0","t1","t2","t3","h0","h1","p0","p1"].map(id=>({id,label:id,side:"right" as const})),w:90,h:80},
  "pir-sensor": {type:"pir-sensor",label:"PIR Motion",category:"Sensors",inputs:[],outputs:["out","valid"].map(id=>({id,label:id,side:"right" as const})),w:80,h:56},
  "current-sensor": {type:"current-sensor",label:"INA219",category:"Sensors",inputs:["en"].map(id=>({id,label:id,side:"left" as const})),outputs:["d0","d1","d2","d3","valid"].map(id=>({id,label:id,side:"right" as const})),w:90,h:70},
  "color-sensor": {type:"color-sensor",label:"TCS3200",category:"Sensors",inputs:["s0","s1","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["r","g","b","freq"].map(id=>({id,label:id,side:"right" as const})),w:90,h:70},
  "strain-gauge": {type:"strain-gauge",label:"Strain Gge",category:"Sensors",inputs:[],outputs:["d0","d1","d2","d3"].map(id=>({id,label:id,side:"right" as const})),w:80,h:56},
  "tilt-sensor": {type:"tilt-sensor",label:"Tilt Sw",category:"Sensors",inputs:[],outputs:["out"].map(id=>({id,label:id,side:"right" as const})),w:70,h:44},
  "reed-sensor": {type:"reed-sensor",label:"Reed Sw",category:"Sensors",inputs:[],outputs:["out"].map(id=>({id,label:id,side:"right" as const})),w:70,h:44},

  // ====== Advanced Actuators ======
  "esc": {type:"esc",label:"ESC",category:"Actuators",inputs:["signal","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["motor"].map(id=>({id,label:id,side:"right" as const})),w:80,h:56},
  "motor-driver": {type:"motor-driver",label:"L298N",category:"Actuators",inputs:["in1","in2","in3","in4","enA","enB"].map(id=>({id,label:id,side:"left" as const})),outputs:["out1","out2","out3","out4"].map(id=>({id,label:id,side:"right" as const})),w:110,h:90},
  "robotic-arm-6dof": {type:"robotic-arm-6dof",label:"6DOF Arm",category:"Actuators",inputs:["j0","j1","j2","j3","j4","j5","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["done","pos0","pos1"].map(id=>({id,label:id,side:"right" as const})),w:110,h:100},
  "pneumatic-cylinder": {type:"pneumatic-cylinder",label:"Pneum Cyl",category:"Actuators",inputs:["in","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["pos"].map(id=>({id,label:id,side:"right" as const})),w:80,h:56},

  // ====== Advanced Electronic ======
  "mosfet-driver": {type:"mosfet-driver",label:"MOSFET Drv",category:"Electronic",inputs:["in","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["gate","fault"].map(id=>({id,label:id,side:"right" as const})),w:80,h:56},
  "relay-module": {type:"relay-module",label:"Relay Mod",category:"Electronic",inputs:["in0","in1","in2","in3","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["com0","com1","com2","com3"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},

  // ====== Robotics ======
  "wheel-mecanum": {type:"wheel-mecanum",label:"Mecanum",category:"Robotics",inputs:["fl","fr","rl","rr"].map(id=>({id,label:id,side:"left" as const})),outputs:["dir"].map(id=>({id,label:id,side:"right" as const})),w:90,h:70},
  "wheel-omni": {type:"wheel-omni",label:"Omni Wheel",category:"Robotics",inputs:["x","y","rot"].map(id=>({id,label:id,side:"left" as const})),outputs:["dir"].map(id=>({id,label:id,side:"right" as const})),w:80,h:60},
  "chassis-frame": {type:"chassis-frame",label:"Chassis",category:"Robotics",inputs:["fl","fr","rl","rr"].map(id=>({id,label:id,side:"left" as const})),outputs:["enc0","enc1","enc2","enc3"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "industrial-6axis": {type:"industrial-6axis",label:"6-Axis Bot",category:"Robotics",inputs:["j0","j1","j2","j3","j4","j5","clk","en","rst"].map(id=>({id,label:id,side:"left" as const})),outputs:["x","y","z","rx","ry","rz","done"].map(id=>({id,label:id,side:"right" as const})),w:120,h:110},
  "scara-arm": {type:"scara-arm",label:"SCARA",category:"Robotics",inputs:["j0","j1","j2","z","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["x","y","done"].map(id=>({id,label:id,side:"right" as const})),w:100,h:90},
  "delta-robot": {type:"delta-robot",label:"Delta Bot",category:"Robotics",inputs:["j0","j1","j2","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["x","y","z","done"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "gripper": {type:"gripper",label:"2-F Gripper",category:"Robotics",inputs:["open","close","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["pos","gripping"].map(id=>({id,label:id,side:"right" as const})),w:80,h:56},
  "gripper-3f": {type:"gripper-3f",label:"3-F Grip",category:"Robotics",inputs:["f0","f1","f2","force","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["pos","gripping","done"].map(id=>({id,label:id,side:"right" as const})),w:90,h:70},
  "encoder": {type:"encoder",label:"Encoder",category:"Robotics",inputs:["ch_a","ch_b","rst"].map(id=>({id,label:id,side:"left" as const})),outputs:["count","dir","speed"].map(id=>({id,label:id,side:"right" as const})),w:80,h:56},
  "lidar": {type:"lidar",label:"LIDAR",category:"Robotics",inputs:["en","scan"].map(id=>({id,label:id,side:"left" as const})),outputs:["dist","angle","valid","done"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "imu": {type:"imu",label:"IMU 6-Axis",category:"Robotics",inputs:["en","clk"].map(id=>({id,label:id,side:"left" as const})),outputs:["ax","ay","az","gx","gy","gz","valid"].map(id=>({id,label:id,side:"right" as const})),w:100,h:90},
  "gps-rtk": {type:"gps-rtk",label:"RTK GPS",category:"Robotics",inputs:["en","clk"].map(id=>({id,label:id,side:"left" as const})),outputs:["lat0","lat1","lon0","lon1","fix","valid"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "bluetooth-rc": {type:"bluetooth-rc",label:"BT RC",category:"Robotics",inputs:["en"].map(id=>({id,label:id,side:"left" as const})),outputs:["fwd","rev","left","right","btn0","btn1","connected"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "wifi-rc": {type:"wifi-rc",label:"WiFi RC",category:"Robotics",inputs:["en","clk"].map(id=>({id,label:id,side:"left" as const})),outputs:["fwd","rev","left","right","speed0","speed1","connected"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "pid-controller": {type:"pid-controller",label:"PID",category:"Robotics",inputs:["setpoint","feedback","kp0","kp1","ki","kd","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["output","error","done"].map(id=>({id,label:id,side:"right" as const})),w:110,h:90},
  "kinematic-solver": {type:"kinematic-solver",label:"IK Solve",category:"Robotics",inputs:["tx","ty","tz","clk","en","rst"].map(id=>({id,label:id,side:"left" as const})),outputs:["j0","j1","j2","j3","j4","j5","done"].map(id=>({id,label:id,side:"right" as const})),w:110,h:100},
  "path-planner": {type:"path-planner",label:"Path Plan",category:"Robotics",inputs:["sx","sy","gx","gy","clk","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["px","py","step","done"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "collision-detector": {type:"collision-detector",label:"Col Det",category:"Robotics",inputs:["x0","x1","y0","y1","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["collision","dist","dir"].map(id=>({id,label:id,side:"right" as const})),w:90,h:70},
  "gimbal": {type:"gimbal",label:"Gimbal",category:"Robotics",inputs:["pan","tilt","en","stabilize"].map(id=>({id,label:id,side:"left" as const})),outputs:["pan_out","tilt_out","locked"].map(id=>({id,label:id,side:"right" as const})),w:90,h:70},
  "rover-diff": {type:"rover-diff",label:"Diff Rover",category:"Robotics",inputs:["lmotor","rmotor","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["speed","turn","enc_l","enc_r"].map(id=>({id,label:id,side:"right" as const})),w:90,h:70},
  "tracked-base": {type:"tracked-base",label:"Tracked",category:"Robotics",inputs:["lmotor","rmotor","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["speed","turn","enc_l","enc_r"].map(id=>({id,label:id,side:"right" as const})),w:90,h:70},
  "drone-quad": {type:"drone-quad",label:"Quadcopter",category:"Robotics",inputs:["throttle","roll","pitch","yaw","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["m1","m2","m3","m4","armed"].map(id=>({id,label:id,side:"right" as const})),w:100,h:80},
  "flight-ctrl": {type:"flight-ctrl",label:"Flight Ctrl",category:"Robotics",inputs:["ax","ay","az","gx","gy","gz","rc0","rc1","rc2","rc3","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["m1","m2","m3","m4","mode","armed"].map(id=>({id,label:id,side:"right" as const})),w:120,h:110},
  "propeller-motor": {type:"propeller-motor",label:"Prop Motor",category:"Robotics",inputs:["throttle","dir"].map(id=>({id,label:id,side:"left" as const})),outputs:["rpm","current"].map(id=>({id,label:id,side:"right" as const})),w:80,h:60},
  "linear-guide": {type:"linear-guide",label:"Lin Guide",category:"Robotics",inputs:["pos","speed","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["position","home","limit"].map(id=>({id,label:id,side:"right" as const})),w:90,h:56},
  "stepper-nema": {type:"stepper-nema",label:"NEMA Stepper",category:"Robotics",inputs:["step","dir","en","ms1","ms2"].map(id=>({id,label:id,side:"left" as const})),outputs:["position","moving"].map(id=>({id,label:id,side:"right" as const})),w:90,h:70},
  "harmonic-drive": {type:"harmonic-drive",label:"Harm Drive",category:"Robotics",inputs:["input","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["output","torque"].map(id=>({id,label:id,side:"right" as const})),w:80,h:56},
  "lead-screw": {type:"lead-screw",label:"Lead Screw",category:"Robotics",inputs:["motor","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["position","force"].map(id=>({id,label:id,side:"right" as const})),w:80,h:56},

  // ====== Industrial ======
  "plc-controller": {type:"plc-controller",label:"PLC",category:"Industrial",inputs:["i0","i1","i2","i3","i4","i5","i6","i7","clk","rst"].map(id=>({id,label:id,side:"left" as const})),outputs:["q0","q1","q2","q3","q4","q5","q6","q7","done"].map(id=>({id,label:id,side:"right" as const})),w:120,h:110},
  "plc-io-module": {type:"plc-io-module",label:"PLC I/O",category:"Industrial",inputs:["i0","i1","i2","i3","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["q0","q1","q2","q3"].map(id=>({id,label:id,side:"right" as const})),w:90,h:70},
  "vfd-drive": {type:"vfd-drive",label:"VFD Drive",category:"Industrial",inputs:["speed","en","dir"].map(id=>({id,label:id,side:"left" as const})),outputs:["u","v","w","fault"].map(id=>({id,label:id,side:"right" as const})),w:90,h:70},
  "servo-drive": {type:"servo-drive",label:"Servo Drv",category:"Industrial",inputs:["pos","vel","en"].map(id=>({id,label:id,side:"left" as const})),outputs:["cmd","fb","done"].map(id=>({id,label:id,side:"right" as const})),w:90,h:70},
  "proximity-switch": {type:"proximity-switch",label:"Prox Sw",category:"Industrial",inputs:[],outputs:["out","npn","pnp"].map(id=>({id,label:id,side:"right" as const})),w:80,h:56},

};

export function portPos(
  nx: number, ny: number, gtype: GateType, portId: string, side: "left" | "right"
): { x: number; y: number } {
  const def = GATE_DEFS[gtype];
  if (!def) return { x: nx, y: ny };
  const ports = side === "left" ? def.inputs : def.outputs;
  const idx = ports.findIndex((p) => p.id === portId);
  if (idx === -1) return { x: nx + (side === "left" ? 0 : def.w), y: ny + def.h / 2 };
  const gap = def.h / (ports.length + 1);
  return {
    x: nx + (side === "left" ? 0 : def.w),
    y: ny + gap * (idx + 1),
  };
}

export const CATEGORIES = [
  "Input Controls", "Output Controls", "Logic Gates", "Combinational", "Sequential",
  "Sensors", "Processors", "Memory", "Communication", "Power", "Electronic", "Actuators",
  "Boards", "Robotics", "Industrial",
] as const;